# OpenAI and Claude rules, derived from Sukka's Ruleset
# Source: https://ruleset.skk.moe/List/non_ip/ai.conf
# Upstream: https://github.com/SukkaW/Surge
# License: AGPL-3.0
# Upstream last updated: 2026-08-07T06:33:36.625Z
# Modified: 2026-09-07
# Changes: retain only OpenAI/ChatGPT/Sora and Claude/Anthropic entries.
# Removed Google, xAI/Grok, other AI services and the upstream marker.
# Static snapshot; no automatic upstream synchronization.
# Size: 9

DOMAIN-SUFFIX,chat.com
DOMAIN-SUFFIX,sora.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,claude.com
DOMAIN-SUFFIX,chatgpt.com
DOMAIN-SUFFIX,chatgpt.site
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,oaistatic.com
DOMAIN-KEYWORD,openai
